name: Okta Terraform
on: 
  push:
      branches:
        - master
  pull_request:

defaults:
  run:
    shell: bash
    
jobs:
  Terraform-Init:
    runs-on: macos-latest
    steps:  
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true
      
      - name: Terraform Apply
        id: apply
        run: terraform apply
        continue-on-error: false
