name: Okta Terraform
on: [push]

defaults:
  run:
    shell: bash
    
jobs:
  Terraform-Init:
    runs-on: macos-latest
    
    steps:  
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
    
      - name: Terraform fmt
        id: fmt
        working-directory: main
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working-directory: main
        run: terraform init

      - name: Terraform Validate
        working-directory: main
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: main
        run: terraform plan
        continue-on-error: true
      
      - name: Terraform Apply
        id: apply
        working-directory: main
        run: terraform apply
        continue-on-error: false
