name: Okta Terraform
on: [push]

defaults:
  run:
    shell: bash
    
jobs:
  Terraform-Init:
    runs-on: macos-latest
    
    
    steps:  
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Dir
        id: CD
        run: echo "For work Directory"
             terraform -chdir=okta-terraform/main
        continue-on-error: false
     
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: terraform init
        continue-on-error: false

      - name: Terraform Validate
        id: validate
        run: terraform validate
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: false
      
      - name: Terraform Apply
        id: apply
        run: terraform apply
        continue-on-error: false
